# Form implementation generated from reading ui file 'D:\programs\aris_chatbot\QTUISave\main_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1126, 737)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setTabletTracking(False)
        MainWindow.setFocusPolicy(QtCore.Qt.ClickFocus)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: #101014;")
        self.verticalLayout = QtWidgets.QVBoxLayout(MainWindow)
        self.verticalLayout.setContentsMargins(9, -1, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.arisChatbotLayout = QtWidgets.QVBoxLayout()
        self.arisChatbotLayout.setObjectName("arisChatbotLayout")
        self.serviceZoneLayout = QtWidgets.QHBoxLayout()
        self.serviceZoneLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.serviceZoneLayout.setObjectName("serviceZoneLayout")
        self.windowMiniumButton = QtWidgets.QPushButton(parent=MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.windowMiniumButton.sizePolicy().hasHeightForWidth())
        self.windowMiniumButton.setSizePolicy(sizePolicy)
        self.windowMiniumButton.setStyleSheet("color: rgb(255, 255, 255)")
        self.windowMiniumButton.setObjectName("windowMiniumButton")
        self.serviceZoneLayout.addWidget(self.windowMiniumButton)
        self.windowMaxButton = QtWidgets.QPushButton(parent=MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.windowMaxButton.sizePolicy().hasHeightForWidth())
        self.windowMaxButton.setSizePolicy(sizePolicy)
        self.windowMaxButton.setStyleSheet("color: rgb(255, 255, 255)")
        self.windowMaxButton.setObjectName("windowMaxButton")
        self.serviceZoneLayout.addWidget(self.windowMaxButton)
        self.exitButton = QtWidgets.QPushButton(parent=MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exitButton.sizePolicy().hasHeightForWidth())
        self.exitButton.setSizePolicy(sizePolicy)
        self.exitButton.setStyleSheet("color: rgb(255, 255, 255)")
        self.exitButton.setObjectName("exitButton")
        self.serviceZoneLayout.addWidget(self.exitButton)
        self.serviceZoneLayout.setStretch(0, 1)
        self.serviceZoneLayout.setStretch(1, 1)
        self.serviceZoneLayout.setStretch(2, 1)
        self.arisChatbotLayout.addLayout(self.serviceZoneLayout)
        self.mainLayout = QtWidgets.QHBoxLayout()
        self.mainLayout.setObjectName("mainLayout")
        self.menuLayout = QtWidgets.QVBoxLayout()
        self.menuLayout.setObjectName("menuLayout")
        self.mainLayout.addLayout(self.menuLayout)
        self.contentLayout = QtWidgets.QVBoxLayout()
        self.contentLayout.setObjectName("contentLayout")
        self.mainLayout.addLayout(self.contentLayout)
        self.mainLayout.setStretch(0, 1)
        self.mainLayout.setStretch(1, 5)
        self.arisChatbotLayout.addLayout(self.mainLayout)
        self.arisChatbotLayout.setStretch(0, 1)
        self.arisChatbotLayout.setStretch(1, 20)
        self.verticalLayout.addLayout(self.arisChatbotLayout)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.windowMiniumButton, self.windowMaxButton)
        MainWindow.setTabOrder(self.windowMaxButton, self.exitButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Form"))
        self.windowMiniumButton.setText(_translate("MainWindow", "—"))
        self.windowMaxButton.setText(_translate("MainWindow", "口"))
        self.exitButton.setText(_translate("MainWindow", "X"))
